//Counter
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

//List
export const ADD_TEXT = 'CHANGE_TEXT';

//ListOperation
export const ADD_OPERATION_TEXT = 'ADD_OPERATION_TEXT';
export const OPERATION_COMPLETED = 'OPERATION_COMPLETED';
